### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by voorhs** [deeppavlov/AutoIntent#22]
## Воспроизведение

Коммит 77a0d2499c02e21841e02a5d23b266a3b7003c5e

В терминале
```bash
autointent mode=multilabel multilabel_path="data/multi_label_data/eurlex-5shot.json"
```

Падает на
- всех версиях eurlex (5shot, 10shot, 20shot)
- на `eurlex.json`
- на всех `reuters.json`, `reuters-10shot.json`, `reuters-20shot.json`

## Проблема

```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.41 GiB. GPU 0 has a total capacity of 5.79 GiB of which 721.81 MiB is free. Including non-PyTorch memory, this process has 5.07 GiB memory in use. Of the allocated memory 4.93 GiB is allocated by PyTorch, and 26.09 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Падает почти сразу после сообщения логгера:
```
[2024-10-17 21:08:11,132][sentence_transformers.SentenceTransformer][INFO] - Load pretrained SentenceTransformer: deepvk/USER-bge-m3
```

## Возможное решение

В случае eurlex и reuters cкорее всего дело в том, что тексты слишком длинные. Хорошо было бы добавить возможность обрезать слишком длинные тексты (как некоторый параметр в конфиге оптимизации например). Такой функционал предоставляет библиотека `sentence transformers` которая и используется в [векторном индексе](https://github.com/deeppavlov/AutoIntent/blob/77a0d2499c02e21841e02a5d23b266a3b7003c5e/autointent/context/vector_index_client/vector_index.py#L13), что-то вроде параметра `truncation=True` в конструкторе.

В случае events скорее всего просто датасет слишком большой (много семплов), потому что на все few-shot версии спокойно прогоняются.

**Comment by Samoed** [comment]
Можно просто передать max_tokens. Тут проблема возникает в том, что bge-m3 имеет 8к токенов контекста и просто такой контекст не влезает в память. А на комитах до работает?
